language: cpp

compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libboost1.55-all-dev 
  - sudo apt-get install -qq libssl-dev
  - sudo apt-get install -qq gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
#  - sudo apt-get -y install binutils-gold
  - g++ -v
  - clang -v
script:
  # Abort build on failure
  - set -e
  - scons 
notifications:
  email:
    false
